// Generate the secrets the self-hosted stack needs, with zero dependencies.
//
//   node deploy/gen-keys.mjs
//
// Prints a ready-to-paste block for deploy/.env:
//   - POSTGRES_PASSWORD  : random db password
//   - JWT_SECRET         : the signing secret shared by auth + rest + storage
//   - ANON_KEY           : public API key (role: anon)   — signed with JWT_SECRET
//   - SERVICE_ROLE_KEY   : admin API key (role: service_role) — keep secret
//
// The anon/service keys ARE JWTs (that's what Supabase keys are): a signed
// token carrying a role claim. PostgREST/Storage verify them with JWT_SECRET.
import { createHmac, randomBytes } from 'node:crypto';

const b64url = (buf) =>
  Buffer.from(buf).toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');

function signJwt(payload, secret) {
  const header = b64url(JSON.stringify({ alg: 'HS256', typ: 'JWT' }));
  const body = b64url(JSON.stringify(payload));
  const data = `${header}.${body}`;
  const sig = b64url(createHmac('sha256', secret).update(data).digest());
  return `${data}.${sig}`;
}

const jwtSecret = randomBytes(32).toString('hex');
const pgPassword = randomBytes(18).toString('base64').replace(/[^a-zA-Z0-9]/g, '').slice(0, 24);

// 10-year tokens — fine for an internal appliance you control.
const iat = 1700000000;                 // fixed issue time (no clock needed)
const exp = iat + 60 * 60 * 24 * 3650;  // +10 years

const anon = signJwt({ role: 'anon', iss: 'supabase', iat, exp }, jwtSecret);
const service = signJwt({ role: 'service_role', iss: 'supabase', iat, exp }, jwtSecret);

console.log(`# --- generated by deploy/gen-keys.mjs --- paste into deploy/.env ---
POSTGRES_PASSWORD=${pgPassword}
JWT_SECRET=${jwtSecret}
ANON_KEY=${anon}
SERVICE_ROLE_KEY=${service}`);
